# SimpleCommandBlocker - Configuration File
# This file is used to configure the plugin settings and messages.

Settings:
  block-all-commands: false
  block-namespaced-commands: true
  sound: "ENTITY_VILLAGER_NO" # https://jd.papermc.io/paper/1.21.1/org/bukkit/Sound.html
  blocked-commands:
    - version
    - ver
    - plugins
    - pl
    - icanhasbukkit
    - thiscommandisnotblockedforvip
    - thiscommandisnotblockedformvp
    - "?" # If command uses a symbol or special character, use the command in quotes.
  groups:
    mvp: # (Permission: simpleblocker.group.mvp)
      - thiscommandisnotblockedformvp
    vip: # (Permission: simpleblocker.group.vip)
      - thiscommandisnotblockedforvip
Messages:
  blocked-message: "<red>This command is blocked"
  blocked-actionbar: "<red>This command is blocked"
  unknown-command-message: "<red>Unknown command."
  unknown-command-actionbar: "<red>Unknown command."